Living/Controllers/LivingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Living.Controllers
{
    public class LivingController : Controller
    {
        // GET: Living
        public ActionResult Test()
        {
            ViewBag.Name = "Abhisit";
            ViewBag.Age = 30;

            return View();
        }

        public ActionResult Test2()
        {
            return View();
        }

        public ActionResult Example()
        {
            return View();
        }
    }
}

Living/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Living Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/living.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LIVING Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li><a href="@Url.Action("Test","Living")">Test</a></li>
                    <li><a href="@Url.Action("Example","Living")">Example</a></li>
                    <li><a href="@Url.Action("Index","House")">House</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Living</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/living.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>